version: 2
jobs:
  build:
    docker: #执行容器
      - image: circleci/node:10 #依赖环境
    branches: #分支
      only:
      - master
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - add_ssh_keys:
          fingerprints:
            - '6f:b2:7f:9d:14:5c:70:fe:4d:96:31:f8:9e:70:6e:01'
      - checkout # 从githun拉去代码
      # 使用缓存
      - restore_cache:
          key: node-dependens # 这个key和save_cache的key相对应，表示使用的是这个key对应的缓存
      - run: 
          name: Install
          command: yarn install
      # 设置缓存
      - save_cache:
          key: node-dependens
          paths:
            - node_modules
      - run:
          name: Build
          command: yarn build
      # 如果出现权限问题，请加上权限设置任务，给脚本添加执行权限，然后再执行发布任务
      - run:
          name: AuthSet
          command: chmod +x ./circleci-deploy.sh
  
      - run:
          name: Deploy
          command: ./circleci-deploy.sh